version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blog_db
    ports:
      - "27017:27017"
    volumes:
      - ./modules/docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app_net

  # Node.js API (MongoDB)
  node_api:
    image: varlopecar/express_mongodb_app_ynov:latest
    container_name: node_api
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017/blog_db?authSource=admin
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - app_net

  # Mongo Express pour l'administration
  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    networks:
      - app_net

networks:
  app_net:
    driver: bridge 