name: CI on Dispatch

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  terraform_env:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan
      - name: Terraform apply
        run: terraform apply --auto-approve
      - name: Docker ps
        run: docker ps && sleep 15
      - name: Check all services are up
        run: |
          chmod +x ../../script.sh
          ../../script.sh
      - name: Docker ps
        run: docker ps
      - name: Terraform destroy
        run: terraform destroy --auto-approve 