name: Test Dispatches

on:
  workflow_dispatch:
    inputs:
      test_repo:
        description: 'Repository to test dispatch'
        required: true
        default: 'express-mongodb-app'
        type: choice
        options:
        - express-mongodb-app
        - react-form

jobs:
  test_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Test dispatch to ${{ github.event.inputs.test_repo }}
        run: |
          echo "Testing dispatch to ${{ github.event.inputs.test_repo }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_DISPATCH }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/varlopecar/${{ github.event.inputs.test_repo }}/dispatches \
            -d '{"event_type": "test-dispatch"}' \
            -w "\nHTTP Status: %{http_code}\nResponse: %{response_code}\n"
          
          if [ $? -eq 0 ]; then
            echo "✅ Dispatch sent successfully to ${{ github.event.inputs.test_repo }}"
          else
            echo "❌ Failed to send dispatch to ${{ github.event.inputs.test_repo }}"
            exit 1
          fi

  test_both_dispatches:
    runs-on: ubuntu-latest
    steps:
      - name: Test dispatch to express-mongodb-app
        run: |
          echo "Testing dispatch to express-mongodb-app"
          response=$(curl -s -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_DISPATCH }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/varlopecar/express-mongodb-app/dispatches \
            -d '{"event_type": "test-dispatch"}')
          
          http_code="${response: -3}"
          if [ "$http_code" = "204" ]; then
            echo "✅ Dispatch to express-mongodb-app: SUCCESS (HTTP $http_code)"
          else
            echo "❌ Dispatch to express-mongodb-app: FAILED (HTTP $http_code)"
            exit 1
          fi

      - name: Test dispatch to react-form
        run: |
          echo "Testing dispatch to react-form"
          response=$(curl -s -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_DISPATCH }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/varlopecar/react-form/dispatches \
            -d '{"event_type": "test-dispatch"}')
          
          http_code="${response: -3}"
          if [ "$http_code" = "204" ]; then
            echo "✅ Dispatch to react-form: SUCCESS (HTTP $http_code)"
          else
            echo "❌ Dispatch to react-form: FAILED (HTTP $http_code)"
            exit 1
          fi 