name: Test Express MongoDB Only

on:
  workflow_dispatch:
  push:
    paths:
      - 'modules/docker/test-express-only.tf'
      - '.github/workflows/test-express-only.yml'

jobs:
  test_express_mongodb:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -target=module.docker_environment

      - name: Terraform apply
        run: terraform apply -auto-approve -target=module.docker_environment

      - name: Wait for services
        run: sleep 15

      - name: Test services
        run: |
          chmod +x ../../test-express-only.sh
          ../../test-express-only.sh

      - name: Show container status
        run: docker ps

      - name: Terraform destroy
        if: always()
        run: terraform destroy -auto-approve -target=module.docker_environment

  dispatch_to_express_mongodb_app:
    needs: test_express_mongodb
    runs-on: ubuntu-latest
    steps:
      - name: Fire event to express-mongodb-app
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_DISPATCH }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/varlopecar/express-mongodb-app/dispatches \
            -d '{"event_type": "trigger-ci"}' 